<#
.SYNOPSIS
  Extract a stable catalog of normative requirements from the specification.

.DESCRIPTION
  Scans every Normative document (Document Class: Normative) for RFC 2119
  statements (SHALL / SHOULD / MAY / MUST / REQUIRED / RECOMMENDED / OPTIONAL,
  case-sensitive) and emits a Markdown requirements index. Each requirement gets
  a stable ID of the form <MNEMONIC>-R<nn>, numbered per document in reading
  order. Code blocks and the document header are skipped.

  This is the reproducible source of truth for REQUIREMENTS-INDEX.md.

.PARAMETER Root
  Repository root. Defaults to the parent of this script's folder.

.EXAMPLE
  pwsh tools/mu-requirements.ps1 > REQUIREMENTS-INDEX.md
#>
[CmdletBinding()]
param(
  [string]$Root = (Split-Path -Parent (Split-Path -Parent $PSCommandPath))
)

$Mnemonic = @{
  'Meta-Universe-Constitution' = 'MUC'; 'Governance' = 'GOV'; 'Change-Process' = 'CHG';
  'Conformance' = 'CONF'; 'Definitions' = 'DEF'; 'Terminology' = 'TERM';
  'MMAS-Core' = 'MMAS-CORE'; 'MMAS-Conformance' = 'MMAS-CONF'; 'MMAS-Package' = 'MMAS-PKG';
  'MMAS-Interchange' = 'MUIF'; 'Versioning' = 'VER'; 'Naming-Conventions' = 'NAME';
  'Traceability' = 'TRACE'; 'Extension-Model' = 'EXT'; 'Validation' = 'VAL';
  'Data-Portability-and-Access' = 'DATAPO';
  'MUFP' = 'MUFP'; 'MUFP-Messages' = 'MUFPM'; 'Identity-Binding' = 'IDB'; 'Federation-Contracts' = 'FEDC';
  'Trust-Model' = 'TRUST'; 'Consent-and-Disclosure' = 'DISC'; 'Semantic-Mapping' = 'MAP';
  'Synchronization' = 'SYNC'; 'Conflict-Resolution' = 'CONFL'; 'Federation-Lifecycle' = 'FEDL';
  'Federation-Profiles' = 'FEDP'; 'Universe' = 'UNI'; 'Dimension' = 'DIM';
  'Namespace' = 'NS'; 'Identity' = 'ID'; 'Object' = 'OBJ'; 'Relationship' = 'REL';
  'Event' = 'EVT'; 'Contract' = 'CON'; 'Projection' = 'PROJ'; 'Context' = 'CTX';
  'Lifecycle' = 'LIFE'
}

$kwPattern = '\b(SHALL NOT|SHALL|SHOULD NOT|SHOULD|MUST NOT|MUST|MAY|REQUIRED|RECOMMENDED|OPTIONAL)\b'

function Get-Level([string]$line) {
  if ($line -cmatch '\bSHALL NOT\b' -or $line -cmatch '\bMUST NOT\b' -or $line -cmatch '\bSHALL\b' -or $line -cmatch '\bMUST\b' -or $line -cmatch '\bREQUIRED\b') { return 'SHALL' }
  if ($line -cmatch '\bSHOULD NOT\b' -or $line -cmatch '\bSHOULD\b' -or $line -cmatch '\bRECOMMENDED\b') { return 'SHOULD' }
  return 'MAY'
}

$files = Get-ChildItem -Path $Root -Recurse -Filter *.md |
  Where-Object { $_.FullName -notmatch '\\\.git\\' } |
  Sort-Object FullName

$totalDocs = 0
$totalReqs = 0
$sb = New-Object System.Text.StringBuilder

foreach ($f in $files) {
  $lines = Get-Content -LiteralPath $f.FullName -Encoding UTF8
  $isNormative = ($lines | Where-Object { $_ -match 'Document Class:.*Normative' }) -ne $null
  if (-not $isNormative) { continue }

  $base = [IO.Path]::GetFileNameWithoutExtension($f.Name)
  $mn = $Mnemonic[$base]
  if (-not $mn) { $mn = ($base.ToUpper() -replace '[^A-Z0-9]', '').Substring(0, [Math]::Min(6, ($base -replace '[^A-Za-z0-9]','').Length)) }

  $rel = $f.FullName.Substring($Root.Length).TrimStart('\','/') -replace '\\','/'
  $section = ''
  $inFence = $false
  $n = 0
  $rows = New-Object System.Collections.Generic.List[string]

  foreach ($line in $lines) {
    if ($line -match '^\s*```') { $inFence = -not $inFence; continue }
    if ($inFence) { continue }
    if ($line -match '^#{1,6}\s+(.*)$') { $section = $Matches[1].Trim(); continue }
    if ($line -cmatch $kwPattern) {
      # skip the header metadata lines
      if ($line -match '^\*\*(Document|Title|Status|Version|Normative|Informative|Copyright|License)') { continue }
      $n++
      $id = "$mn-R{0:D2}" -f $n
      $level = Get-Level $line
      $stmt = $line.Trim()
      $stmt = $stmt -replace '\[([^\]]+)\]\([^)]+\)', '$1'   # flatten markdown links to their text
      $stmt = $stmt -replace '\|', '\|'
      if ($stmt.Length -gt 160) { $stmt = $stmt.Substring(0, 157) + '...' }
      $sec = ($section -replace '\|','\|')
      $rows.Add(('| `{0}` | {1} | {2} | {3} |' -f $id, $level, $sec, $stmt))
    }
  }

  if ($rows.Count -eq 0) { continue }
  $totalDocs++
  $totalReqs += $rows.Count
  [void]$sb.AppendLine(('## {0} -- `{1}`  ({2} requirements)' -f $base, $rel, $rows.Count))
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('| ID | Level | Section | Statement |')
  [void]$sb.AppendLine('|----|-------|---------|-----------|')
  foreach ($r in $rows) { [void]$sb.AppendLine($r) }
  [void]$sb.AppendLine('')
}

$intro = New-Object System.Text.StringBuilder
[void]$intro.AppendLine('# Requirements Index')
[void]$intro.AppendLine('')
[void]$intro.AppendLine('Auto-generated by the requirements tool (`mu-requirements`). Do not edit by hand; regenerate instead.')
[void]$intro.AppendLine('')
[void]$intro.AppendLine(('_{0} requirements across {1} normative documents._' -f $totalReqs, $totalDocs))
[void]$intro.AppendLine('')
[void]$intro.AppendLine('Stable catalog of every RFC 2119 normative statement in the Normative documents.')
[void]$intro.AppendLine('IDs have the form `<MNEMONIC>-R<nn>`, numbered per document in reading order.')
[void]$intro.AppendLine('Tooling, Conformance and Validation reference these IDs.')
[void]$intro.AppendLine('')
Write-Output ($intro.ToString() + $sb.ToString())
[Console]::Error.WriteLine("Extracted $totalReqs requirements from $totalDocs normative documents.")
